---
- name: Copy provider config
  ansible.builtin.copy:
    src: files/provider.tf
    dest: "{{ playbook_dir }}/tf/provider.tf"
    owner: root
    group: root
    mode: "0644"

- name: Create terraform credentials file
  ansible.builtin.template:
    src: credentials.auto.tfvars.j2
    dest: "{{ playbook_dir }}/tf/credentials.auto.tfvars"
    owner: root
    group: root
    mode: "0644"

- name: Copy cloud metadata config
  ansible.builtin.copy:
    src: files/cloud_metadata_cfg.yaml
    dest: "{{ playbook_dir }}/tf/cloud_metadata_cfg.yaml"
    owner: root
    group: root
    mode: "0644"

- name: Substitute cloud_init userdata
  ansible.builtin.template:
    src: cloud_userdata_cfg.yaml.j2
    dest: "{{ playbook_dir }}/tf/cloud_userdata_cfg.yaml"
    mode: "0600"

- name: Substitute resources tf
  ansible.builtin.template:
    src: terraform_vm_resources.tf.j2
    dest: "{{ playbook_dir }}/tf/vm.tf"
    mode: "0600"

- name: Init Terraform
  ansible.builtin.shell: |
    cd {{ playbook_dir }}/tf;
    terraform init
  when: (operation == "init")
  register: init

- name: "Display output: Init Terraform"
  ansible.builtin.debug:
    msg: "{{ init.stdout }}"
  when: (operation == "init")

- name: Create resources - Plan
  ansible.builtin.shell: |
    cd {{ playbook_dir }}/tf;
    terraform workspace new {{ env }}
    terraform workspace select {{ env }}
    terraform plan -out=plan.tfplan;
  when: (operation == "create-plan")
  register: create_plan

- name: "Display output: Create resources - Plan"
  ansible.builtin.debug:
    msg: "{{ create_plan.stdout }}"
  when: (operation == "create-plan")

- name: Create resources
  ansible.builtin.shell: |
    cd {{ playbook_dir }}/tf;
    terraform workspace select {{ env }}
    terraform apply plan.tfplan
  when: (operation == "create")
  register: create

- name: "Display output: Create resources"
  ansible.builtin.debug:
    msg: "{{ create.stdout }}"
  when: (operation == "create")

- name: Destroy resources
  ansible.builtin.shell: |
    cd {{ playbook_dir }}/tf;
    terraform workspace new {{ env }}
    terraform workspace select {{ env }}
    terraform destroy -auto-approve
  when: (operation == "destroy")
  register: destroy

- name: "Display output: Destroy resources"
  ansible.builtin.debug:
    msg: "{{ destroy.stdout }}"
  when: (operation == "destroy")
