# cloud-config
local-hostname: ${hostname}
instance-id: ${hostname}
network:
  version: 2
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - ${ipv4_addr_cidr}
      gateway4: ${ipv4_gateway}
      nameservers:
        addresses:
          - ${ipv4_gateway}
          - 8.8.8.8
          - 8.8.4.4
